- provider: gae
    keyfile: ../credentials.json
    project: DEFINIR
    on:
      branch: main
before_install:
- openssl aes-256-cbc -K $encrypted_45197dc6f6a9_key -iv $encrypted_45197dc6f6a9_iv
  -in credentials.json.enc -out ../credentials.json -d

