{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.7.9"
  ],
  "install": [
    "pip install flask"
  ],
  "script": [
    "python -m unittest -v test || travis_terminate 1;"
  ],
  "deploy": [
    {
      "provider": "heroku",
      "strategy": "api",
      "api_key": "$HEROKU_API_KEY",
      "edge": true,
      "app": "devopslab-gilmarvagner",
      "on": {
        "branch": [
          "main"
        ]
      }
    }
  ]
}
