# Linguagem 
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

addons:
 sonarcloud:
  organization: gilmarvagner
  token: ${SONAR_TOKEN}

before_install:
- openssl aes-256-cbc -K $encrypted_45197dc6f6a9_key -iv $encrypted_45197dc6f6a9_iv
  -in credentials.json.enc -out ../credentials.json -d
jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage

      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
         script:
        - python -m unittest -v test || travis_terminate 1;
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-gilmarvagner
        on:
          branch: main



    - stage: STG TEST
      script:
        - curl https://devopslab-gilmarvagner.herokuapp.com/ | grep Hello || travis_terminate 1;
     
    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../credentials.json
        project: lab-devops-cloud-315600
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devops-cloud-315600.uc.r.appspot.com/ | grep Hello || travis_terminate 1;
      
   
